export enum EmessageMapping {
    ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
    CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
    INVENTORY_NOT_FOUND = 'INVENTORY_NOT_FOUND',
    DEFAULT = 'DEFAULT',
    DEFAULT_ERROR = "DEFAULT_ERROR",
    ITEM_UPDATED = "ITEM_UPDATED"
}